[package]
name = "hashsig-host"
version = "0.1.0"
edition = "2021"

[lib]
name = "hashsig_host"
crate-type = ["staticlib"]

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
hashsig = { git = "https://github.com/b-wagn/hash-sig", branch = "main" }
rand = "0.9"
paste = "1.0.15"

[build-dependencies]
cbindgen = "0.26"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
